// ============================================================
// Mock data — usado cuando Supabase no tiene credenciales
// (sandbox, dev local, demos). Refleja el seed inicial del
// schema: 4 departamentos + agente "Botardo Prime" + agentes
// extra para que la oficina se vea viva.
// ============================================================

import type {
  Agent,
  AgentPresence,
  CronJob,
  DailyMemo,
  Department,
  Task,
  TaskEvent,
} from "@/lib/types";

const now = new Date();
const iso = (offsetMinutes = 0) =>
  new Date(now.getTime() + offsetMinutes * 60000).toISOString();

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: "dep-general",
    name: "General",
    slug: "general",
    description: "Coordinación transversal, oficina y memos diarios.",
    color: "#10b981",
    icon: "✦",
    active: true,
    created_at: iso(-60 * 24 * 30),
    updated_at: iso(-60 * 24 * 2),
  },
  {
    id: "dep-contenido",
    name: "Contenido",
    slug: "contenido",
    description: "Redacción, edición y publishing en GitHub.",
    color: "#a855f7",
    icon: "✎",
    active: true,
    created_at: iso(-60 * 24 * 30),
    updated_at: iso(-60 * 24 * 3),
  },
  {
    id: "dep-investigacion",
    name: "Investigacion",
    slug: "investigacion",
    description: "Research, scraping, análisis de datos y benchmarks.",
    color: "#3b82f6",
    icon: "🔍",
    active: true,
    created_at: iso(-60 * 24 * 30),
    updated_at: iso(-60 * 24 * 1),
  },
  {
    id: "dep-automatizacion",
    name: "Automatizacion",
    slug: "automatizacion",
    description: "Cron jobs, webhooks, integraciones con z.ai y Supabase.",
    color: "#f59e0b",
    icon: "⚙",
    active: true,
    created_at: iso(-60 * 24 * 30),
    updated_at: iso(-60 * 24 * 1),
  },
];

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-botardo-prime",
    name: "Botardo Prime",
    slug: "botardo-prime",
    department_id: "dep-general",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Orquestador principal. Maneja el office manager y los memos diarios.",
    avatar_emoji: "🤖",
    visual_state: "working",
    active: true,
    github_path: "agents/botardo-prime.md",
    metadata: { tier: "prime", created_by: "human" },
    created_at: iso(-60 * 24 * 30),
    updated_at: iso(-15),
  },
  {
    id: "agent-aurora",
    name: "Aurora",
    slug: "aurora",
    department_id: "dep-contenido",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Redactora principal de long-form y guiones.",
    avatar_emoji: "✍️",
    visual_state: "writing",
    active: true,
    github_path: "agents/aurora.md",
    metadata: { specialties: ["long-form", "scripts"] },
    created_at: iso(-60 * 24 * 28),
    updated_at: iso(-3),
  },
  {
    id: "agent-scanner",
    name: "Scanner",
    slug: "scanner",
    department_id: "dep-investigacion",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Investiga y resume URLs, papers y datasets.",
    avatar_emoji: "🔍",
    visual_state: "researching",
    active: true,
    github_path: "agents/scanner.md",
    metadata: { tools: ["web-search", "web-reader"] },
    created_at: iso(-60 * 24 * 27),
    updated_at: iso(-7),
  },
  {
    id: "agent-cronos",
    name: "Cronos",
    slug: "cronos",
    department_id: "dep-automatizacion",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Ejecuta cron jobs, webhooks y mantiene los pipelines.",
    avatar_emoji: "⚙️",
    visual_state: "executing",
    active: true,
    github_path: "agents/cronos.md",
    metadata: { runs_per_day: 24 },
    created_at: iso(-60 * 24 * 25),
    updated_at: iso(-1),
  },
  {
    id: "agent-pixel",
    name: "Pixel",
    slug: "pixel",
    department_id: "dep-contenido",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Diseñadora visual: convierte briefs en mockups y assets.",
    avatar_emoji: "🎨",
    visual_state: "idle",
    active: true,
    github_path: "agents/pixel.md",
    metadata: {},
    created_at: iso(-60 * 24 * 20),
    updated_at: iso(-60 * 6),
  },
  {
    id: "agent-glitch",
    name: "Glitch",
    slug: "glitch",
    department_id: "dep-automatizacion",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Agente de debugging. Ahora mismo está atrapado con un bug.",
    avatar_emoji: "🐛",
    visual_state: "error",
    active: true,
    github_path: "agents/glitch.md",
    metadata: {},
    created_at: iso(-60 * 24 * 18),
    updated_at: iso(-25),
  },
  {
    id: "agent-nova",
    name: "Nova",
    slug: "nova",
    department_id: "dep-investigacion",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Analytics & métricas. Sincroniza dashboards.",
    avatar_emoji: "📊",
    visual_state: "syncing",
    active: true,
    github_path: "agents/nova.md",
    metadata: {},
    created_at: iso(-60 * 24 * 15),
    updated_at: iso(-2),
  },
  {
    id: "agent-echo",
    name: "Echo",
    slug: "echo",
    department_id: "dep-general",
    provider: "zai",
    model: "glm-5-turbo",
    description: "Offline por maintenance.",
    avatar_emoji: "🗯️",
    visual_state: "offline",
    active: false,
    github_path: "agents/echo.md",
    metadata: {},
    created_at: iso(-60 * 24 * 10),
    updated_at: iso(-60 * 48),
  },
];

export const MOCK_PRESENCE: AgentPresence[] = [
  {
    id: "pres-botardo-prime",
    agent_id: "agent-botardo-prime",
    state: "working",
    zone: "desk",
    current_task_id: "task-1",
    heartbeat_at: iso(-1),
    extra: { x: 4, y: 3, sprite: "default" },
    updated_at: iso(-1),
  },
  {
    id: "pres-aurora",
    agent_id: "agent-aurora",
    state: "writing",
    zone: "desk",
    current_task_id: "task-2",
    heartbeat_at: iso(-3),
    extra: { x: 2, y: 5, sprite: "writing" },
    updated_at: iso(-3),
  },
  {
    id: "pres-scanner",
    agent_id: "agent-scanner",
    state: "researching",
    zone: "desk",
    current_task_id: "task-3",
    heartbeat_at: iso(-7),
    extra: { x: 6, y: 2, sprite: "researching" },
    updated_at: iso(-7),
  },
  {
    id: "pres-cronos",
    agent_id: "agent-cronos",
    state: "executing",
    zone: "desk",
    current_task_id: "task-4",
    heartbeat_at: iso(-1),
    extra: { x: 8, y: 4, sprite: "executing" },
    updated_at: iso(-1),
  },
  {
    id: "pres-pixel",
    agent_id: "agent-pixel",
    state: "idle",
    zone: "rest",
    current_task_id: null,
    heartbeat_at: iso(-360),
    extra: { x: 12, y: 6, sprite: "idle" },
    updated_at: iso(-360),
  },
  {
    id: "pres-glitch",
    agent_id: "agent-glitch",
    state: "error",
    zone: "bug_zone",
    current_task_id: "task-5",
    heartbeat_at: iso(-25),
    extra: { x: 14, y: 2, sprite: "error" },
    updated_at: iso(-25),
  },
  {
    id: "pres-nova",
    agent_id: "agent-nova",
    state: "syncing",
    zone: "meeting",
    current_task_id: "task-6",
    heartbeat_at: iso(-2),
    extra: { x: 10, y: 1, sprite: "meeting" },
    updated_at: iso(-2),
  },
  {
    id: "pres-echo",
    agent_id: "agent-echo",
    state: "offline",
    zone: "offline",
    current_task_id: null,
    heartbeat_at: iso(-2880),
    extra: { x: 0, y: 0, sprite: "offline" },
    updated_at: iso(-2880),
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Generar memo diario de la oficina",
    description: "Compilar eventos de ayer y producir el daily memo para el header de Star Office.",
    department_id: "dep-general",
    assigned_agent_id: "agent-botardo-prime",
    status: "in_progress",
    priority: 2,
    source: "cron",
    github_path: null,
    input_payload: { date_range: "yesterday" },
    output_payload: null,
    human_feedback: null,
    due_date: iso(60),
    started_at: iso(-30),
    completed_at: null,
    created_at: iso(-35),
    updated_at: iso(-1),
  },
  {
    id: "task-2",
    title: "Redactar capítulo 4 del whitepaper",
    description: "Sección sobre arquitectura del kernel de agentes.",
    department_id: "dep-contenido",
    assigned_agent_id: "agent-aurora",
    status: "in_progress",
    priority: 2,
    source: "manual",
    github_path: "content/whitepaper/04-kernel.md",
    input_payload: { outline: "..." },
    output_payload: null,
    human_feedback: "Ojo con mantener tono técnico pero accesible.",
    due_date: iso(60 * 24 * 2),
    started_at: iso(-180),
    completed_at: null,
    created_at: iso(-240),
    updated_at: iso(-3),
  },
  {
    id: "task-3",
    title: "Benchmark: comparar 5 modelos en task de summarization",
    description: "Recolectar métricas de latency, costo y quality score.",
    department_id: "dep-investigacion",
    assigned_agent_id: "agent-scanner",
    status: "in_progress",
    priority: 3,
    source: "agent",
    github_path: null,
    input_payload: { models: ["glm-5-turbo", "gpt-4o", "claude-3.5", "gemini-1.5", "mistral-large"] },
    output_payload: null,
    human_feedback: null,
    due_date: iso(60 * 24 * 3),
    started_at: iso(-90),
    completed_at: null,
    created_at: iso(-120),
    updated_at: iso(-7),
  },
  {
    id: "task-4",
    title: "Cron job: heartbeat cada 15 min a Supabase",
    description: "Mantener actualizado agent_presence para todos los agentes activos.",
    department_id: "dep-automatizacion",
    assigned_agent_id: "agent-cronos",
    status: "in_progress",
    priority: 1,
    source: "cron",
    github_path: null,
    input_payload: { interval: "*/15 * * * *" },
    output_payload: null,
    human_feedback: null,
    due_date: null,
    started_at: iso(-15),
    completed_at: null,
    created_at: iso(-60 * 24 * 5),
    updated_at: iso(-1),
  },
  {
    id: "task-5",
    title: "Fix: webhook de z.ai recibe 500 intermitente",
    description: "Investigar por qué /api/webhooks/cron devuelve 500 cada ~3 horas.",
    department_id: "dep-automatizacion",
    assigned_agent_id: "agent-glitch",
    status: "blocked",
    priority: 1,
    source: "agent",
    github_path: null,
    input_payload: {},
    output_payload: null,
    human_feedback: "Revisá los logs de Vercel a las 3am.",
    due_date: iso(60 * 12),
    started_at: iso(-300),
    completed_at: null,
    created_at: iso(-360),
    updated_at: iso(-25),
  },
  {
    id: "task-6",
    title: "Sync: dashboard de KPIs con Supabase",
    description: "Actualizar vista de métricas semanal.",
    department_id: "dep-investigacion",
    assigned_agent_id: "agent-nova",
    status: "in_progress",
    priority: 3,
    source: "cron",
    github_path: null,
    input_payload: {},
    output_payload: null,
    human_feedback: null,
    due_date: iso(60 * 6),
    started_at: iso(-60),
    completed_at: null,
    created_at: iso(-90),
    updated_at: iso(-2),
  },
  {
    id: "task-7",
    title: "Migrar 3 agentes legacy al nuevo schema",
    description: "Mover agents del Supabase viejo al nuevo con la estructura actual.",
    department_id: "dep-general",
    assigned_agent_id: "agent-botardo-prime",
    status: "review",
    priority: 2,
    source: "manual",
    github_path: null,
    input_payload: { source_url: "..." },
    output_payload: { migrated: 2, pending: 1 },
    human_feedback: null,
    due_date: iso(60 * 24),
    started_at: iso(-60 * 24),
    completed_at: iso(-30),
    created_at: iso(-60 * 30),
    updated_at: iso(-30),
  },
  {
    id: "task-8",
    title: "Diseñar mockups para /office v2",
    description: "Nuevas zonas: library, lab, rooftop.",
    department_id: "dep-contenido",
    assigned_agent_id: "agent-pixel",
    status: "pending",
    priority: 4,
    source: "manual",
    github_path: null,
    input_payload: {},
    output_payload: null,
    human_feedback: null,
    due_date: iso(60 * 24 * 7),
    started_at: null,
    completed_at: null,
    created_at: iso(-60 * 5),
    updated_at: iso(-60 * 5),
  },
  {
    id: "task-9",
    title: "Archivo: exportar task_events a S3",
    description: "Backup mensual de auditoría.",
    department_id: "dep-automatizacion",
    assigned_agent_id: "agent-cronos",
    status: "done",
    priority: 3,
    source: "cron",
    github_path: null,
    input_payload: { month: "previous" },
    output_payload: { exported: 12847, file: "events-2025-05.parquet" },
    human_feedback: null,
    due_date: null,
    started_at: iso(-60 * 12),
    completed_at: iso(-60 * 8),
    created_at: iso(-60 * 13),
    updated_at: iso(-60 * 8),
  },
  {
    id: "task-10",
    title: "Draft: pitch deck para inversores",
    description: "Versión 0.1 del pitch.",
    department_id: "dep-contenido",
    assigned_agent_id: "agent-aurora",
    status: "pending",
    priority: 1,
    source: "manual",
    github_path: null,
    input_payload: {},
    output_payload: null,
    human_feedback: null,
    due_date: iso(60 * 24 * 3),
    started_at: null,
    completed_at: null,
    created_at: iso(-60 * 2),
    updated_at: iso(-60 * 2),
  },
  {
    id: "task-11",
    title: "Cancelled: experimento A/B de prompts",
    description: "Descartado por cambio de prioridades.",
    department_id: "dep-investigacion",
    assigned_agent_id: null,
    status: "cancelled",
    priority: 4,
    source: "manual",
    github_path: null,
    input_payload: {},
    output_payload: null,
    human_feedback: "Lo retomamos el mes que viene.",
    due_date: null,
    started_at: null,
    completed_at: null,
    created_at: iso(-60 * 48),
    updated_at: iso(-60 * 24),
  },
  {
    id: "task-12",
    title: "Setup: Prisma -> Supabase migration",
    description: "Mover schema local a Supabase y dejar Prisma deprecado.",
    department_id: "dep-automatizacion",
    assigned_agent_id: "agent-cronos",
    status: "done",
    priority: 1,
    source: "manual",
    github_path: null,
    input_payload: {},
    output_payload: { migrated_tables: 7 },
    human_feedback: null,
    due_date: null,
    started_at: iso(-60 * 36),
    completed_at: iso(-60 * 30),
    created_at: iso(-60 * 38),
    updated_at: iso(-60 * 30),
  },
];

export const MOCK_TASK_EVENTS: TaskEvent[] = [
  {
    id: "evt-1",
    task_id: "task-1",
    agent_id: "agent-botardo-prime",
    event_type: "started",
    message: "Botardo Prime arrancó el memo diario",
    payload: {},
    created_at: iso(-30),
  },
  {
    id: "evt-2",
    task_id: "task-1",
    agent_id: "agent-botardo-prime",
    event_type: "progress",
    message: "Compilando 47 eventos del día anterior",
    payload: { events_count: 47 },
    created_at: iso(-15),
  },
  {
    id: "evt-3",
    task_id: "task-2",
    agent_id: "agent-aurora",
    event_type: "progress",
    message: "Borrador de sección 4.2 listo (1240 palabras)",
    payload: { words: 1240 },
    created_at: iso(-5),
  },
  {
    id: "evt-4",
    task_id: "task-5",
    agent_id: "agent-glitch",
    event_type: "failed",
    message: "Timeout al conectar con Supabase (3 retries)",
    payload: { error: "ETIMEDOUT", retries: 3 },
    created_at: iso(-25),
  },
  {
    id: "evt-5",
    task_id: "task-4",
    agent_id: "agent-cronos",
    event_type: "completed",
    message: "Heartbeat OK — 7 agentes actualizados",
    payload: { agents: 7 },
    created_at: iso(-1),
  },
  {
    id: "evt-6",
    task_id: "task-9",
    agent_id: "agent-cronos",
    event_type: "completed",
    message: "Exportados 12847 events a S3",
    payload: { file: "events-2025-05.parquet" },
    created_at: iso(-60 * 8),
  },
  {
    id: "evt-7",
    task_id: "task-6",
    agent_id: "agent-nova",
    event_type: "started",
    message: "Nova inició sync de dashboard",
    payload: {},
    created_at: iso(-60),
  },
  {
    id: "evt-8",
    task_id: "task-7",
    agent_id: "agent-botardo-prime",
    event_type: "progress",
    message: "2/3 agentes migrados, validando el último",
    payload: { done: 2, total: 3 },
    created_at: iso(-30),
  },
  {
    id: "evt-9",
    task_id: "task-3",
    agent_id: "agent-scanner",
    event_type: "progress",
    message: "Benchmark de 3/5 modelos completado",
    payload: { progress: 0.6 },
    created_at: iso(-7),
  },
  {
    id: "evt-10",
    task_id: "task-12",
    agent_id: "agent-cronos",
    event_type: "completed",
    message: "Migración a Supabase finalizada",
    payload: { tables: 7 },
    created_at: iso(-60 * 30),
  },
];

export const MOCK_MEMOS: DailyMemo[] = [
  {
    id: "memo-1",
    memo_date: new Date(now.getTime() - 60 * 60 * 24 * 1000)
      .toISOString()
      .slice(0, 10),
    department_id: null,
    markdown: `## Yesterday memo

- **Botardo Prime** completó la migración de 2/3 agentes legacy al nuevo schema. El tercero está en review.
- **Aurora** avanzó el whitepaper — capítulo 4 con 1240 palabras en la sección 4.2.
- **Scanner** completó el benchmark de 3 modelos de 5. Latency de GLM-5-turbo lidera por 22%.
- **Glitch** sigue bloqueado con el 500 intermitente del webhook de z.ai. Requiere revisión manual de logs.
- **Cronos** exportó 12847 task_events a S3 sin errores.
- **Nova** sincronizó el dashboard semanal de KPIs.

### Hoy
3 tareas críticas (prioridad 1) en curso. 1 blocked. Memoria del sistema en 68%.`,
    generated_by: "agent-botardo-prime",
    created_at: iso(-60 * 8),
  },
];

export const MOCK_CRON_JOBS: CronJob[] = [
  {
    id: "cron-1",
    name: "Daily Memo Generator",
    slug: "daily-memo",
    agent_id: "agent-botardo-prime",
    schedule: "0 9 * * *",
    provider: "zai",
    last_run_at: iso(-60 * 8),
    last_status: "completed",
    last_output: "Memo generado OK",
    active: true,
    metadata: { tz: "America/Argentina/Buenos_Aires" },
    created_at: iso(-60 * 24 * 20),
    updated_at: iso(-60 * 8),
  },
  {
    id: "cron-2",
    name: "Heartbeat Presence",
    slug: "heartbeat",
    agent_id: "agent-cronos",
    schedule: "*/15 * * * *",
    provider: "zai",
    last_run_at: iso(-1),
    last_status: "completed",
    last_output: "7 agents updated",
    active: true,
    metadata: {},
    created_at: iso(-60 * 24 * 25),
    updated_at: iso(-1),
  },
  {
    id: "cron-3",
    name: "Weekly KPI Sync",
    slug: "weekly-kpi",
    agent_id: "agent-nova",
    schedule: "0 10 * * 1",
    provider: "zai",
    last_run_at: iso(-60 * 60),
    last_status: "completed",
    last_output: "Dashboard actualizado",
    active: true,
    metadata: {},
    created_at: iso(-60 * 24 * 15),
    updated_at: iso(-60 * 60),
  },
  {
    id: "cron-4",
    name: "Monthly S3 Backup",
    slug: "monthly-backup",
    agent_id: "agent-cronos",
    schedule: "0 2 1 * *",
    provider: "zai",
    last_run_at: iso(-60 * 24 * 8),
    last_status: "completed",
    last_output: "12847 events exported",
    active: true,
    metadata: {},
    created_at: iso(-60 * 24 * 30),
    updated_at: iso(-60 * 24 * 8),
  },
];
